package doremi;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class financialIndicators implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public financialIndicators() {
    }




}