package doremi;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class financialIndicators implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Profitability")
	private java.lang.String profitability;
	@org.kie.api.definition.type.Label(value = "Debt Paying Ability")
	private java.lang.String debtpaying;
	@org.kie.api.definition.type.Label(value = "Operation Ability")
	private java.lang.String operationability;
	@org.kie.api.definition.type.Label(value = "Liquidity")
	private java.lang.String liquidity;

	public financialIndicators() {
	}

	public java.lang.String getProfitability() {
		return this.profitability;
	}

	public void setProfitability(java.lang.String profitability) {
		this.profitability = profitability;
	}

	public java.lang.String getDebtpaying() {
		return this.debtpaying;
	}

	public void setDebtpaying(java.lang.String debtpaying) {
		this.debtpaying = debtpaying;
	}

	public java.lang.String getOperationability() {
		return this.operationability;
	}

	public void setOperationability(java.lang.String operationability) {
		this.operationability = operationability;
	}

	public java.lang.String getLiquidity() {
		return this.liquidity;
	}

	public void setLiquidity(java.lang.String liquidity) {
		this.liquidity = liquidity;
	}

	public financialIndicators(java.lang.String profitability,
			java.lang.String debtpaying, java.lang.String operationability,
			java.lang.String liquidity) {
		this.profitability = profitability;
		this.debtpaying = debtpaying;
		this.operationability = operationability;
		this.liquidity = liquidity;
	}

}