package model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InventoryDecision implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public InventoryDecision() {
    }




}