package doremi;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Customer")
	private java.lang.Integer customerID;
	@org.kie.api.definition.type.Label("Is Corporate")
	private java.lang.Boolean isCorporate;
	@org.kie.api.definition.type.Label("Credit Risk")
	private java.lang.String creditRisk;
	@org.kie.api.definition.type.Label("Financial Indicator ID")
	private financialIndicators financialIndicatorID;
	@org.kie.api.definition.type.Label("Customer Name")
	private java.lang.String customerName;
	@org.kie.api.definition.type.Label("Customer Address")
	private java.lang.String customerAddress;
	@org.kie.api.definition.type.Label("Date Registered")
	private java.time.LocalDateTime dateRegistered;
	@org.kie.api.definition.type.Label("Late Payment")
	private java.lang.Boolean latePayment;
	@org.kie.api.definition.type.Label("Defaulter")
	private java.lang.Boolean defaulter;
	@org.kie.api.definition.type.Label("is New")
	private java.lang.Boolean isNew;
	@org.kie.api.definition.type.Label("Years Active")
	private java.lang.Integer yearsActive;
	@org.kie.api.definition.type.Label("LTV")
	private java.lang.Float ltv;
	@org.kie.api.definition.type.Label("Frequency of Purchase")
	private java.lang.String frequencyOfPurchase;

	public Customer() {
	}

	public java.lang.Integer getCustomerID() {
		return this.customerID;
	}

	public void setCustomerID(java.lang.Integer customerID) {
		this.customerID = customerID;
	}

	public java.lang.Boolean getIsCorporate() {
		return this.isCorporate;
	}

	public void setIsCorporate(java.lang.Boolean isCorporate) {
		this.isCorporate = isCorporate;
	}

	public java.lang.String getCreditRisk() {
		return this.creditRisk;
	}

	public void setCreditRisk(java.lang.String creditRisk) {
		this.creditRisk = creditRisk;
	}

	public java.lang.String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(java.lang.String customerName) {
		this.customerName = customerName;
	}

	public java.lang.String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(java.lang.String customerAddress) {
		this.customerAddress = customerAddress;
	}

	public java.time.LocalDateTime getDateRegistered() {
		return this.dateRegistered;
	}

	public void setDateRegistered(java.time.LocalDateTime dateRegistered) {
		this.dateRegistered = dateRegistered;
	}

	public java.lang.Boolean getLatePayment() {
		return this.latePayment;
	}

	public void setLatePayment(java.lang.Boolean latePayment) {
		this.latePayment = latePayment;
	}

	public java.lang.Boolean getDefaulter() {
		return this.defaulter;
	}

	public void setDefaulter(java.lang.Boolean defaulter) {
		this.defaulter = defaulter;
	}

	public java.lang.Boolean getIsNew() {
		return this.isNew;
	}

	public void setIsNew(java.lang.Boolean isNew) {
		this.isNew = isNew;
	}

	public java.lang.Integer getYearsActive() {
		return this.yearsActive;
	}

	public void setYearsActive(java.lang.Integer yearsActive) {
		this.yearsActive = yearsActive;
	}

	public java.lang.Float getLtv() {
		return this.ltv;
	}

	public void setLtv(java.lang.Float ltv) {
		this.ltv = ltv;
	}

	public java.lang.String getFrequencyOfPurchase() {
		return this.frequencyOfPurchase;
	}

	public void setFrequencyOfPurchase(java.lang.String frequencyOfPurchase) {
		this.frequencyOfPurchase = frequencyOfPurchase;
	}

	public doremi.financialIndicators getFinancialIndicatorID() {
		return this.financialIndicatorID;
	}

	public void setFinancialIndicatorID(
			doremi.financialIndicators financialIndicatorID) {
		this.financialIndicatorID = financialIndicatorID;
	}

	public Customer(java.lang.Integer customerID,
			java.lang.Boolean isCorporate, java.lang.String creditRisk,
			doremi.financialIndicators financialIndicatorID,
			java.lang.String customerName, java.lang.String customerAddress,
			java.time.LocalDateTime dateRegistered,
			java.lang.Boolean latePayment, java.lang.Boolean defaulter,
			java.lang.Boolean isNew, java.lang.Integer yearsActive,
			java.lang.Float ltv, java.lang.String frequencyOfPurchase) {
		this.customerID = customerID;
		this.isCorporate = isCorporate;
		this.creditRisk = creditRisk;
		this.financialIndicatorID = financialIndicatorID;
		this.customerName = customerName;
		this.customerAddress = customerAddress;
		this.dateRegistered = dateRegistered;
		this.latePayment = latePayment;
		this.defaulter = defaulter;
		this.isNew = isNew;
		this.yearsActive = yearsActive;
		this.ltv = ltv;
		this.frequencyOfPurchase = frequencyOfPurchase;
	}

}